import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/footer";
import ControllerNavbar from "./component/navbar/controllernav";
import { getNameSession } from "@/app/libs/cookie";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MenuSoft",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const name = await getNameSession()
  const sesion = process.env.SISTEMNAME

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <header>
            <ControllerNavbar name={name} sesion={sesion} />
          </header>
          <main className="flex-grow">
            {children}
          </main>
          <footer>
            <Footer sesion={sesion} />
          </footer>
        </div>
      </body>
    </html>
  );
}
