
import { redirect } from 'next/navigation'
import NavUSuario from "./component/navegacion";
import { getNameSessionAlumno } from '../libs/cookieAlumos';

const sesion = process.env.SISTEMNAME

export const metadata = {
  title: "MenuSoft",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const user = await getNameSessionAlumno()

  if (!user) {
    return redirect('/')
  }
  return (
    <section>
      <NavUSuario sesion={sesion} user={user} />
      {children}
    </section>
  );
}
